apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-backend
spec:
  selector:
    matchLabels:
      app: password-backend
  template:
    metadata:
      labels:
        app: password-backend
    spec:
      containers:
      - name: password-backend
        image: 515966499694.dkr.ecr.sa-east-1.amazonaws.com/devops-eks-password-svc/backend:v10
        ports:
        - containerPort: 80
