apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-frontend
spec:
  selector:
    matchLabels:
      app: password-frontend
  template:
    metadata:
      labels:
        app: password-frontend
    spec:
      containers:
      - name: password-frontend
        image: 515966499694.dkr.ecr.sa-east-1.amazonaws.com/devops-eks-password-svc/frontend:v11
        ports:
        - containerPort: 80
